Registro
linea-it/docs pull request #53
Opened 2023-10-26 20:00 UTC by gschwend

2023-10-30 14:34 UTC, marianapfernandes requested changes

2023-10-30 14:34 UTC, marianapfernandes commented on docs/registro.md
> +* Login com credenciais institucionaia (feito através da CAFE) - Indicado para quem tem vínculo institucional, por oferecer mais recursos de processamento e armazenamento.
**correção:** institucionais (feito através da CAFe). Indicado...

2023-10-30 14:34 UTC, marianapfernandes commented on docs/sci-platforms/index.md
> +Durante a operação do levantamento [LSST](http://lsst.org), o LSP será o principal ponto de acesso aos dados para os cientistas da comunidade Brasileira, tanto para os membros do _Brazilian Participa
**correção:** brasileira

2023-10-30 14:34 UTC, marianapfernandes commented on docs/sci-platforms/index.md
>  Para dados embargados, o acesso depende de credenciais específicas. Para saber como criar uma conta no LIneA e ter acesso aos dados, leia a seção [Primeiros Passos](https://docs.linea.org.br/primeiro
alteramos essa seção para "registro"; 
**correção:** leia a seção Registro

2024-04-24 21:11 UTC, carlosadean commented
Vou aprovar essas mudanças, mas teremos que adicionar mais alterações para adequar a documentação às melhorias que fizemos no processo de registro.

2024-04-24 21:11 UTC, merged